import Head from 'next/head'

// export const metadata = {
//   title: 'F.A.Q / Investor mode',
//   description: 'Generated by Next.js',

// }
export default function FaqLayout({ children }) {
    return (
      <>
        <Head>
            <title>F.A.Q | Investor Mode</title>
            <meta name="description" content="F.A.Q Informasi Seputar Crowdfunding UMKM"/>
        </Head>
        {children}
      </>
    );
  }
  