import Head from 'next/head'

// export const metadata = {
//   title: 'F.A.Q / Investor mode',
//   description: 'Generated by Next.js',

// }
export default function ProfileLayout({ children }) {
    return (
      <>
        <Head>
            <title>Profile | Investor Mode</title>
            <meta name="description" content="Profile anda pada Crowdfunding."/>
        </Head>
        {children}
      </>
    );
  }
  